### ISSUE TITLE
MPC controller example using a new robot

### ISSUE THREAD

**Issue by nicrusso7** [google-research/motion_imitation#31]
Hello! I'm trying to run the [mpc controller example](https://github.com/google-research/motion_imitation/blob/master/mpc_controller/locomotion_controller_example.py) using a [DIY robot](https://github.com/nicrusso7/rex-gym/blob/feature/mark-II/rex_gym/util/pybullet_data/assets/urdf/rex.urdf).

I was wondering how these values are calculated:

[MPC_BODY_MASS](https://github.com/google-research/motion_imitation/blob/1a141c306e4b3e1173302223ee837813e7878386/mpc_controller/laikago_sim.py#L7)
[MPC_BODY_INERTIA](https://github.com/google-research/motion_imitation/blob/1a141c306e4b3e1173302223ee837813e7878386/mpc_controller/laikago_sim.py#L8)
[MPC_BODY_HEIGHT](https://github.com/google-research/motion_imitation/blob/1a141c306e4b3e1173302223ee837813e7878386/mpc_controller/laikago_sim.py#L9)

I'm also not sure about [`_DEFAULT_HIP_POSITIONS`](https://github.com/google-research/motion_imitation/blob/1a141c306e4b3e1173302223ee837813e7878386/mpc_controller/laikago_sim.py#L21). I understood these are the hip joints positions, however they are slightly different if compared with the URDF values (eg. [this one](https://github.com/bulletphysics/bullet3/blob/bd62a6deac617fdabd94a32034ae73e5e1a7fb46/examples/pybullet/gym/pybullet_data/laikago/laikago_toes_zup.urdf#L58))

thanks!

**Comment by erwincoumans** [comment]
Those values should be similar to the real robot (or URDF file). Since there are sim-to-real differences, they can be tuned to work better on real robot, hence some differences.
In the latest revision, the A1 is also included for MPC, both simulation and real robot.
See https://github.com/google-research/motion_imitation/pull/30

Good luck, and keep us posted if you have any luck tuning the parameters for your robot!
